### ISSUE TITLE
Image_matching_fraction greater than 1 in some cases

### ISSUE THREAD

**Issue by vishalBindal** [disa2019/ImageLocalisation#1]
The image involved in this case was blurry

**Comment by tmibvishal** [comment]
Also, include the 2 images which caused this issue

**Comment by vishalBindal** [comment]
The images are not available right now, they may be obtained by checking check_blurry to false

**Comment by vishalBindal** [comment]
All assignees please arrange for the images.

**Comment by vishalBindal** [comment]
The below image matched with a lot of images with confidence > 1
![image755](https://user-images.githubusercontent.com/45521764/58041533-f38c3700-7b55-11e9-85bb-78f186f7ea6b.jpg)

The below image is one of those many images:
![image205](https://user-images.githubusercontent.com/45521764/58041631-2df5d400-7b56-11e9-8da8-547a0f2f50e5.jpg)

**Comment by tmibvishal** [comment]
**Now I calculate c1 and c2 which doubles the time to match the image**
But it will also give symmetric result irrespective of whether I pass **_img1_** first or **_img2_** first
then I get
```python
return fraction = (c1 + c2) / (a1 + b1)
```
You can pass last variable symmetry_match: bool as False in SURF_match_2 or SURF_match function now

```python
def SURF_match_2(key_des_1,key_des_2, hessianThreshold: int = 400, ratio_thresh: float = 0.7, symmetry_match: bool = True):
    ...
```

Earlier I was only calculating c1
