### ISSUE TITLE
Better image matcher required

### ISSUE THREAD

**Issue by vishalBindal** [disa2019/ImageLocalisation#2]
Image matching is not perfect and detects only solid edges. Soft edges, like clothes or leaves, are not detected

**Comment by tmibvishal** [comment]
This is not an issue but a feature required. Please mark the labels and firstly learn how to use git before creating issues

**Comment by vishalBindal** [comment]
This is an issue as this feature already exists but is not giving ideal results. Thanks for marking the label.

**Comment by tmibvishal** [comment]
Why is nobody trying to solve this issue
@vishalBindal 
@sushantsondhi 
I am closing this issue but do try to still improve it

**Comment by vishalBindal** [comment]
You should try it too
@tmibvishal 
Everyone shares equal responsibility for this
